import { Profile, PromptDefinition, Interest, Activity, ProfileReport, WaitlistCity, ProfileChange, DashboardStats } from './types'

export const mockUsers = [
  {
    id: '1',
    phone: '+1 (555) 123-4567',
    email: 'emma.wilson@email.com',
    is_admin: false,
    is_banned: false,
    created_at: '2024-01-15T10:30:00Z',
    last_seen_at: '2024-01-20T14:22:00Z',
    referral_code: 'EMMA2024',
  },
  {
    id: '2',
    phone: '+1 (555) 234-5678',
    email: 'james.chen@email.com',
    is_admin: false,
    is_banned: false,
    created_at: '2024-01-10T08:15:00Z',
    last_seen_at: '2024-01-19T16:45:00Z',
    referral_code: null,
  },
  {
    id: '3',
    phone: '+1 (555) 345-6789',
    email: null,
    is_admin: false,
    is_banned: true,
    created_at: '2024-01-05T12:00:00Z',
    last_seen_at: '2024-01-18T09:30:00Z',
    referral_code: 'SARAH123',
  },
]

export const mockProfiles: Profile[] = [
  {
    id: '1',
    user_id: '1',
    status: 'live',
    gender: 'woman',
    first_name: 'Emma',
    last_name: 'Wilson',
    age: 28,
    height: 65,
    birthday: '1996-03-15',
    pronouns: 'she/her',
    neighborhood: 'Williamsburg',
    bio: 'Creative director by day, amateur chef by night. Looking for someone who appreciates a good homemade pasta and spontaneous weekend adventures.',
    school: 'NYU',
    job_title: 'Creative Director',
    hometown: 'Boston, MA',
    waitlist_city_id: null,
    completed: true,
    needs_manual_review: false,
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-01-18T14:00:00Z',
    uploads: [
      { id: '1', url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', display_order: 0, type: 'photo' },
      { id: '2', url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400', display_order: 1, type: 'photo' },
      { id: '3', url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400', display_order: 2, type: 'photo' },
    ],
    prompt_responses: [
      {
        id: '1',
        profile_id: '1',
        prompt_definition_id: '1',
        answer: 'My ideal Sunday involves a farmers market trip, cooking brunch with friends, and ending the day with a good book.',
        display_order: 0,
        prompt: { id: '1', prompt: 'My ideal Sunday looks like...', category: 'lifestyle', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z' },
      },
      {
        id: '2',
        profile_id: '1',
        prompt_definition_id: '2',
        answer: "When I learned that pineapple doesn't actually belong on pizza. It was a dark day.",
        display_order: 1,
        prompt: { id: '2', prompt: 'The last time I cried was...', category: 'personality', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z' },
      },
    ],
    interests: [
      { id: '1', name: 'Cooking', category: 'hobbies' },
      { id: '2', name: 'Travel', category: 'lifestyle' },
      { id: '3', name: 'Art', category: 'culture' },
    ],
    activities: [
      { id: '1', name: 'Running', url: '/icons/running.svg' },
      { id: '2', name: 'Yoga', url: '/icons/yoga.svg' },
    ],
    geolocation: { id: '1', profile_id: '1', city: 'Brooklyn', region: 'NY', country: 'USA' },
    user: mockUsers[0],
  },
  {
    id: '2',
    user_id: '2',
    status: 'live',
    gender: 'man',
    first_name: 'James',
    last_name: 'Chen',
    age: 32,
    height: 71,
    birthday: '1992-07-22',
    pronouns: 'he/him',
    neighborhood: 'East Village',
    bio: 'Software engineer who actually leaves the house sometimes. Big fan of live music, craft beer, and hiking. Looking for someone to explore the city with.',
    school: 'Stanford',
    job_title: 'Senior Software Engineer',
    hometown: 'San Francisco, CA',
    waitlist_city_id: null,
    completed: true,
    needs_manual_review: false,
    created_at: '2024-01-10T08:15:00Z',
    updated_at: '2024-01-17T11:30:00Z',
    uploads: [
      { id: '4', url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', display_order: 0, type: 'photo' },
      { id: '5', url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', display_order: 1, type: 'photo' },
    ],
    prompt_responses: [
      {
        id: '3',
        profile_id: '2',
        prompt_definition_id: '3',
        answer: 'I once accidentally joined a flash mob in Times Square because I thought everyone was just really enthusiastic about the crosswalk.',
        display_order: 0,
        prompt: { id: '3', prompt: 'My most embarrassing moment...', category: 'personality', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z' },
      },
    ],
    interests: [
      { id: '4', name: 'Music', category: 'culture' },
      { id: '5', name: 'Hiking', category: 'outdoor' },
      { id: '6', name: 'Technology', category: 'work' },
    ],
    activities: [
      { id: '3', name: 'Concerts', url: '/icons/concert.svg' },
    ],
    geolocation: { id: '2', profile_id: '2', city: 'Manhattan', region: 'NY', country: 'USA' },
    user: mockUsers[1],
  },
  {
    id: '3',
    user_id: '3',
    status: 'waitlisted',
    gender: 'woman',
    first_name: 'Sarah',
    last_name: 'Martinez',
    age: 26,
    height: 63,
    birthday: '1998-11-08',
    pronouns: 'she/her',
    neighborhood: 'Lincoln Park',
    bio: 'Graphic designer with a love for vintage fashion and indie films. My ideal date involves a museum and a cozy coffee shop.',
    school: 'RISD',
    job_title: 'Senior Designer',
    hometown: 'Chicago, IL',
    waitlist_city_id: '2',
    completed: true,
    needs_manual_review: true,
    created_at: '2024-01-05T12:00:00Z',
    updated_at: '2024-01-16T09:00:00Z',
    uploads: [
      { id: '6', url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', display_order: 0, type: 'photo' },
      { id: '7', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', display_order: 1, type: 'photo' },
    ],
    prompt_responses: [
      {
        id: '4',
        profile_id: '3',
        prompt_definition_id: '1',
        answer: 'Flea market hunting, followed by brunch at a spot nobody else has discovered yet, then an afternoon at the Art Institute.',
        display_order: 0,
        prompt: { id: '1', prompt: 'My ideal Sunday looks like...', category: 'lifestyle', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z' },
      },
    ],
    interests: [
      { id: '7', name: 'Design', category: 'work' },
      { id: '8', name: 'Film', category: 'culture' },
      { id: '9', name: 'Fashion', category: 'lifestyle' },
    ],
    activities: [
      { id: '4', name: 'Museums', url: '/icons/museum.svg' },
    ],
    geolocation: { id: '3', profile_id: '3', city: 'Chicago', region: 'IL', country: 'USA' },
    user: mockUsers[2],
  },
  {
    id: '4',
    user_id: '4',
    status: 'banned',
    gender: 'man',
    first_name: 'Mike',
    last_name: 'Thompson',
    age: 29,
    height: 69,
    birthday: '1995-05-20',
    pronouns: 'he/him',
    neighborhood: 'Midtown',
    bio: 'Banned user profile for testing.',
    school: null,
    job_title: 'Marketing Manager',
    hometown: 'Atlanta, GA',
    waitlist_city_id: null,
    completed: true,
    needs_manual_review: false,
    created_at: '2024-01-02T15:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
    uploads: [
      { id: '8', url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', display_order: 0, type: 'photo' },
    ],
    prompt_responses: [],
    interests: [],
    activities: [],
    geolocation: { id: '4', profile_id: '4', city: 'Manhattan', region: 'NY', country: 'USA' },
    user: {
      id: '4',
      phone: '+1 (555) 456-7890',
      email: 'mike.t@email.com',
      is_admin: false,
      is_banned: true,
      created_at: '2024-01-02T15:00:00Z',
      last_seen_at: '2024-01-10T10:00:00Z',
      referral_code: null,
    },
  },
  {
    id: '5',
    user_id: '5',
    status: 'waitlisted',
    gender: 'nonbinary',
    first_name: 'Alex',
    last_name: 'Rivera',
    age: 24,
    height: 67,
    birthday: '2000-02-14',
    pronouns: 'they/them',
    neighborhood: 'Mission District',
    bio: 'Musician and barista. I make great pour-overs and even better playlists. Looking for someone to share late night conversations with.',
    school: 'Berklee',
    job_title: 'Musician',
    hometown: 'Miami, FL',
    waitlist_city_id: '3',
    completed: true,
    needs_manual_review: false,
    created_at: '2024-01-18T09:00:00Z',
    updated_at: '2024-01-19T14:30:00Z',
    uploads: [
      { id: '9', url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400', display_order: 0, type: 'photo' },
      { id: '10', url: 'https://images.unsplash.com/photo-1488161628813-04466f0bb7f6?w=400', display_order: 1, type: 'photo' },
    ],
    prompt_responses: [
      {
        id: '5',
        profile_id: '5',
        prompt_definition_id: '4',
        answer: 'Being able to read minds, but only when people are thinking about food.',
        display_order: 0,
        prompt: { id: '4', prompt: "If I could have one superpower, it'd be...", category: 'fun', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z' },
      },
    ],
    interests: [
      { id: '4', name: 'Music', category: 'culture' },
      { id: '10', name: 'Coffee', category: 'lifestyle' },
    ],
    activities: [
      { id: '3', name: 'Concerts', url: '/icons/concert.svg' },
    ],
    geolocation: { id: '5', profile_id: '5', city: 'San Francisco', region: 'CA', country: 'USA' },
    user: {
      id: '5',
      phone: '+1 (555) 567-8901',
      email: 'alex.r@email.com',
      is_admin: false,
      is_banned: false,
      created_at: '2024-01-18T09:00:00Z',
      last_seen_at: '2024-01-20T11:00:00Z',
      referral_code: 'ALEX2024',
    },
  },
]

export const mockPromptDefinitions: PromptDefinition[] = [
  { id: '1', prompt: 'My ideal Sunday looks like...', category: 'lifestyle', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z', response_count: 342 },
  { id: '2', prompt: 'The last time I cried was...', category: 'personality', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z', response_count: 287 },
  { id: '3', prompt: 'My most embarrassing moment...', category: 'personality', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z', response_count: 412 },
  { id: '4', prompt: "If I could have one superpower, it'd be...", category: 'fun', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z', response_count: 523 },
  { id: '5', prompt: 'A perfect first date for me is...', category: 'dating', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z', response_count: 601 },
  { id: '6', prompt: "The way to my heart is...", category: 'dating', start_date: null, end_date: null, deleted_at: null, created_at: '2024-01-01T00:00:00Z', response_count: 445 },
  { id: '7', prompt: "I'm looking for someone who...", category: 'dating', start_date: '2024-01-15', end_date: '2024-02-15', deleted_at: null, created_at: '2024-01-15T00:00:00Z', response_count: 156 },
  { id: '8', prompt: 'My guilty pleasure is...', category: 'fun', start_date: null, end_date: null, deleted_at: '2024-01-10T00:00:00Z', created_at: '2023-12-01T00:00:00Z', response_count: 234 },
]

export const mockInterests: Interest[] = [
  { id: '1', name: 'Cooking', category: 'hobbies', usage_count: 1234 },
  { id: '2', name: 'Travel', category: 'lifestyle', usage_count: 2156 },
  { id: '3', name: 'Art', category: 'culture', usage_count: 876 },
  { id: '4', name: 'Music', category: 'culture', usage_count: 1987 },
  { id: '5', name: 'Hiking', category: 'outdoor', usage_count: 1432 },
  { id: '6', name: 'Technology', category: 'work', usage_count: 654 },
  { id: '7', name: 'Design', category: 'work', usage_count: 432 },
  { id: '8', name: 'Film', category: 'culture', usage_count: 1098 },
  { id: '9', name: 'Fashion', category: 'lifestyle', usage_count: 765 },
  { id: '10', name: 'Coffee', category: 'lifestyle', usage_count: 1876 },
  { id: '11', name: 'Photography', category: 'hobbies', usage_count: 987 },
  { id: '12', name: 'Reading', category: 'hobbies', usage_count: 1543 },
  { id: '13', name: 'Fitness', category: 'lifestyle', usage_count: 1654 },
  { id: '14', name: 'Gaming', category: 'hobbies', usage_count: 876 },
  { id: '15', name: 'Foodie', category: 'lifestyle', usage_count: 2345 },
]

export const mockActivities: Activity[] = [
  { id: '1', name: 'Running', url: '/icons/running.svg', usage_count: 876 },
  { id: '2', name: 'Yoga', url: '/icons/yoga.svg', usage_count: 1234 },
  { id: '3', name: 'Concerts', url: '/icons/concert.svg', usage_count: 1567 },
  { id: '4', name: 'Museums', url: '/icons/museum.svg', usage_count: 654 },
  { id: '5', name: 'Brunch', url: '/icons/brunch.svg', usage_count: 2134 },
  { id: '6', name: 'Cycling', url: '/icons/cycling.svg', usage_count: 543 },
  { id: '7', name: 'Wine Tasting', url: '/icons/wine.svg', usage_count: 432 },
  { id: '8', name: 'Dancing', url: '/icons/dancing.svg', usage_count: 987 },
]

export const mockReports: ProfileReport[] = [
  {
    id: '1',
    profile_id: '1',
    reported_profile_id: '4',
    reporter_notes: 'This user was sending inappropriate messages and making me uncomfortable.',
    reviewer_notes: null,
    is_resolved: false,
    profile_upload_id: null,
    conversation_id: 'conv_123',
    created_at: '2024-01-19T14:30:00Z',
    reporter: mockProfiles[0],
    reported: mockProfiles[3],
  },
  {
    id: '2',
    profile_id: '2',
    reported_profile_id: '4',
    reporter_notes: 'Profile photos appear to be fake/catfishing.',
    reviewer_notes: 'Verified - photos are stock images. User banned.',
    is_resolved: true,
    profile_upload_id: '8',
    conversation_id: null,
    created_at: '2024-01-18T10:15:00Z',
    reporter: mockProfiles[1],
    reported: mockProfiles[3],
    reported_upload: { id: '8', url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', display_order: 0, type: 'photo' },
  },
  {
    id: '3',
    profile_id: null,
    reported_profile_id: '2',
    reporter_notes: 'Internally flagged - potential policy violation in bio content.',
    reviewer_notes: null,
    is_resolved: false,
    profile_upload_id: null,
    conversation_id: null,
    created_at: '2024-01-20T09:00:00Z',
    reporter: null,
    reported: mockProfiles[1],
  },
]

export const mockWaitlistCities: WaitlistCity[] = [
  { id: '1', name: 'New York', state: 'NY', latitude: 40.7128, longitude: -74.006 },
  { id: '2', name: 'Chicago', state: 'IL', latitude: 41.8781, longitude: -87.6298 },
  { id: '3', name: 'San Francisco', state: 'CA', latitude: 37.7749, longitude: -122.4194 },
  { id: '4', name: 'Los Angeles', state: 'CA', latitude: 34.0522, longitude: -118.2437 },
  { id: '5', name: 'Miami', state: 'FL', latitude: 25.7617, longitude: -80.1918 },
  { id: '6', name: 'Austin', state: 'TX', latitude: 30.2672, longitude: -97.7431 },
]

export const mockProfileChanges: ProfileChange[] = [
  {
    id: '1',
    profile_id: '1',
    field: 'bio',
    old_value: 'Creative director who loves to cook.',
    new_value: 'Creative director by day, amateur chef by night. Looking for someone who appreciates a good homemade pasta and spontaneous weekend adventures.',
    changed_by: 'user',
    changed_at: '2024-01-18T14:00:00Z',
    profile: mockProfiles[0],
  },
  {
    id: '2',
    profile_id: '1',
    field: 'neighborhood',
    old_value: 'Brooklyn',
    new_value: 'Williamsburg',
    changed_by: 'user',
    changed_at: '2024-01-17T11:30:00Z',
    profile: mockProfiles[0],
  },
  {
    id: '3',
    profile_id: '2',
    field: 'job_title',
    old_value: 'Software Engineer',
    new_value: 'Senior Software Engineer',
    changed_by: 'user',
    changed_at: '2024-01-17T11:30:00Z',
    profile: mockProfiles[1],
  },
  {
    id: '4',
    profile_id: '4',
    field: 'status',
    old_value: 'live',
    new_value: 'banned',
    changed_by: 'admin@leftfield.app',
    changed_at: '2024-01-18T16:00:00Z',
    profile: mockProfiles[3],
  },
  {
    id: '5',
    profile_id: '3',
    field: 'status',
    old_value: null,
    new_value: 'waitlisted',
    changed_by: 'system',
    changed_at: '2024-01-05T12:00:00Z',
    profile: mockProfiles[2],
  },
]

export const mockDashboardStats: DashboardStats = {
  total_users: 12847,
  live_profiles: 8234,
  waitlisted_profiles: 4156,
  pending_reports: 23,
  new_users_today: 87,
  new_users_week: 543,
}
